name: look_it_up
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.5.1
  go_router: ^15.1.1
  equatable: ^2.0.7
  http: ^1.3.0
  google_fonts: ^6.2.1
  layout: ^1.0.5
  atlas_icons: ^0.0.12
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true